name: pulmoscan_app
description: "Application mobile de détection des maladies pulmonaires"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.3.0
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8
  tflite_flutter: ^0.12.0
  image: ^4.1.7
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/pulmoscan_model.tflite
